

CREATE TABLE IF NOT EXISTS stand_scouting (
  id SERIAL PRIMARY KEY,
  initals VARCHAR(10),
  match_number SMALLINT,
  teamnum SMALLINT,
  start_position VARCHAR(10),
  no_show BOOL,
  cage_position VARCHAR(10),
  automobile BOOL,
  auto_l1 SMALLINT,
  auto_l2 SMALLINT,
  auto_l3 SMALLINT,
  auto_l4 SMALLINT,
  auto_algae_barge SMALLINT,
  auto_algae_processor SMALLINT,
  auto_algae_dislodged SMALLINT,
  auto_foul SMALLINT,
  tele_algae_dislodged SMALLINT,
  coral_intake VARCHAR(10),
  algae_intake VARCHAR(10),
  tele_l1 SMALLINT,
  tele_l2 SMALLINT,
  tele_l3 SMALLINT,
  tele_l4 SMALLINT,
  tele_algae_barge SMALLINT,
  tele_algae_processor SMALLINT,
  end_position VARCHAR(10),
  touched_opps_cage BOOL,
  coral_RP BOOL,
  barge_RP BOOL,
  auto_RP BOOL,
  offense SMALLINT,
  defense SMALLINT,
  was_defended BOOL,
  died BOOL,
  tipped BOOL,
  card CARD,
  comments VARCHAR(200)
);